### ISSUE TITLE
Can't package for iOS and OS X

### ISSUE THREAD

**Issue by shrx** [MitchTalmadge/Emoji-Tools#27]
I have extracted the images from an android .ttf font (NotoColorEmoji-unhinted).
I would now like to package the font for OS X.
However, the iOS and OS X options are disabled:
![screenshot](http://i.imgur.com/AOHtQEK.png)

**Comment by MitchTalmadge** [comment]
You must find an iOS ttf, extract it, copy the extracted emojis from the Android TTF into the extraction directory of the iOS TTF (overwriting any existing emojis) and then package the iOS directory.

I'm still looking for a better way to do this. The way it works right now is that it uses the original TTF file as a sort of template when packaging, which is why you only get certain options.

Hope this works!

**Comment by shrx** [comment]
Aha, thans for the explanation. I assume it's the same for OS X?

**Comment by MitchTalmadge** [comment]
iOS and OSX fonts are able to be interchanged as there is only one difference between the two; iOS emojis use CgBI encoding, while OSX emojis use RGBA. Emoji Tools can convert them automatically during packaging

**Comment by shrx** [comment]
Thanks, I will try to do something with the built-in Apple Color Emoji ttf.
